import React,{useEffect,useMemo,useState} from "react";
import {Activity,BarChart3,BookOpen,BrainCircuit,BriefcaseBusiness,ChevronRight,FileText,Gauge,GraduationCap,LayoutDashboard,Lightbulb,Menu,Search,Settings,Sparkles,Target,TrendingUp,Upload,UserRound,X,CheckCircle2,AlertTriangle,Clock3,Download} from "lucide-react";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,PieChart,Pie,Cell} from "recharts";

const API="httpS://skillsync-ai-eaev.onrender.com";                          
const fallback={
job_description:"We are looking for a Data Analyst who can work with Python, SQL, Excel and Power BI. The candidate should understand data analysis, statistics and data visualization. Experience with machine learning, cloud computing and Git/GitHub is an advantage. Strong communication and problem-solving skills are required.",
curriculum:"Programming with Python, Database Management and SQL, Statistics, Data Analysis, Web Technologies, Machine Learning fundamentals, Communication Skills, Software Engineering and practical laboratory training.",
job_skills:{Python:92,SQL:85,"Power BI":74,Excel:70,"Data Analysis":74,Statistics:70,"Data Visualization":70,"Machine Learning":62,"Cloud Computing":62,"Git/GitHub":62,Communication:62,"Problem Solving":62},
curriculum_skills:{Python:75,SQL:60,"Data Analysis":72,Statistics:68,"Machine Learning":35,Communication:55},
trends:[
{skill:"Python",demand:92,category:"Programming"},{skill:"SQL",demand:85,category:"Data"},
{skill:"Cloud Computing",demand:82,category:"Cloud"},{skill:"Machine Learning",demand:78,category:"AI/ML"},
{skill:"Power BI",demand:74,category:"Analytics"},{skill:"Data Visualization",demand:70,category:"Analytics"},
{skill:"Git/GitHub",demand:68,category:"Development"},{skill:"React",demand:65,category:"Web"}]};
const nav=[["dashboard","Dashboard",LayoutDashboard],["job","Job Analyzer",FileText],["curriculum","Curriculum",GraduationCap],["gap","Skill Gap",Target],["trends","Industry Trends",TrendingUp],["recommendations","AI Recommendations",Lightbulb],["profile","Student Profile",UserRound],["reports","Reports",BarChart3]];

function App(){
 const [page,setPage]=useState("dashboard"),[mobileOpen,setMobileOpen]=useState(false),[data,setData]=useState(fallback),[apiOnline,setApiOnline]=useState(false);
 useEffect(()=>{fetch(`${API}/api/demo`).then(r=>r.json()).then(d=>{setData(d);setApiOnline(true)}).catch(()=>setApiOnline(false))},[]);
 const gapData=useMemo(()=>[...new Set([...Object.keys(data.job_skills),...Object.keys(data.curriculum_skills)])].map(skill=>{let industry=data.job_skills[skill]||0,curriculum=data.curriculum_skills[skill]||0,gap=Math.max(industry-curriculum,0);return{skill,industry,curriculum,gap,level:gap>=35?"High":gap>=15?"Medium":"Low"}}).sort((a,b)=>b.gap-a.gap),[data]);
 const navigate=p=>{setPage(p);setMobileOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="app">
  <aside className={`sidebar ${mobileOpen?"open":""}`}>
   <div className="brand"><div className="brandIcon"><BrainCircuit size={25}/></div><div><b>SkillSync</b><span>AI Platform</span></div><button className="mobileClose" onClick={()=>setMobileOpen(false)}><X/></button></div>
   <div className="navTitle">MAIN MENU</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>navigate(id)}><Icon size={18}/><span>{label}</span>{page===id&&<ChevronRight className="navArrow" size={15}/>}</button>)}</nav>
   <div className="sidebarBottom"><div className="statusCard"><div className="statusDot"></div><div><strong>{apiOnline?"AI Engine Online":"Demo Mode"}</strong><small>{apiOnline?"FastAPI connected":"Backend can be started locally"}</small></div></div><button className="settings"><Settings size={17}/> Settings</button></div>
  </aside>
  <main className="main"><header className="topbar"><button className="mobileMenu" onClick={()=>setMobileOpen(true)}><Menu/></button><div className="breadcrumb"><span>SkillSync AI</span><ChevronRight size={14}/><strong>{nav.find(x=>x[0]===page)?.[1]}</strong></div><div className="topActions"><div className="searchBox"><Search size={17}/><input placeholder="Search skills..."/></div><div className="avatar">SR</div></div></header>
   <div className="content">
    {page==="dashboard"&&<Dashboard data={data} gapData={gapData} navigate={navigate}/>}
    {page==="job"&&<Analyzer type="job" initial={data.job_description} onResult={skills=>setData(d=>({...d,job_skills:skills}))}/>}
    {page==="curriculum"&&<Analyzer type="curriculum" initial={data.curriculum} onResult={skills=>setData(d=>({...d,curriculum_skills:skills}))}/>}
    {page==="gap"&&<GapPage gapData={gapData}/>}
    {page==="trends"&&<Trends data={data.trends}/>}
    {page==="recommendations"&&<Recommendations gapData={gapData}/>}
    {page==="profile"&&<Profile/>}{page==="reports"&&<Reports data={data} gapData={gapData}/>}
   </div>
  </main>
 </div>
}

function PageHeader({eyebrow,title,desc,action}){return <div className="pageHeader"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Stat({icon:Icon,label,value,delta,tone}){return <div className="stat"><div className={`statIcon ${tone}`}><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong><small>{delta}</small></div></div>}

function Dashboard({data,gapData,navigate}){
 const high=gapData.filter(x=>x.level==="High").length,avg=gapData.length?Math.round(gapData.reduce((a,x)=>a+x.gap,0)/gapData.length):0;
 return <>
 <PageHeader eyebrow="OVERVIEW" title="Industry–Academia Skill Intelligence" desc="Understand what employers need, compare it with your curriculum, and identify priority skill gaps." action={<button className="primary" onClick={()=>navigate("job")}><FileText size={17}/> Analyze a Job</button>}/>
 <div className="hero"><div className="heroText"><div className="heroBadge"><Sparkles size={14}/> AI-POWERED SKILL ANALYSIS</div><h2>Bridge the gap between <span>education</span> and industry.</h2><p> descriptions, extract in-demand skills, compare them with curriculum coverage and generate actionable recommendations.</p><button className="heroButton" onClick={()=>navigate("gap")}>View Skill Gap Analysis <ChevronRight size={17}/></button></div><div className="heroVisual"><div className="orbit o1"></div><div className="orbit o2"></div><div className="brain"><BrainCircuit size={58}/></div><div className="floatCard fc1"><Target size={16}/><span>Gap Detection</span><b>{high} high</b></div><div className="floatCard fc2"><TrendingUp size={16}/><span>Avg. Gap</span><b>{avg}%</b></div></div></div>
 <div className="statsGrid"><Stat icon={BriefcaseBusiness} label="Jobs Analyzed" value="1,240" delta="+18.4%" tone="blue"/><Stat icon={BrainCircuit} label="Skills Detected" value="86" delta="+12.2%" tone="purple"/><Stat Analyze jobicon={Target} label="Skill Gaps" value={gapData.length} delta="Needs review" tone="orange"/><Stat icon={Gauge} label="Alignment Score" value="72%" delta="+6.8%" tone="green"/></div>
 <div className="twoCol"><section className="panel"><div className="panelHead"><div><h3>Top Industry Skills</h3><p>Current demand from analyzed job descriptions</p></div><button className="linkBtn" onClick={()=>navigate("trends")}>View all <ChevronRight size={15}/></button></div><div className="skillBars">{data.trends.slice(0,6).map((x,i)=><div className="barRow" key={x.skill}><div className="barLabel"><span>{i+1}. {x.skill}</span><b>{x.demand}%</b></div><div className="barTrack"><div className="barFill" style={{width:`${x.demand}%`}}></div></div></div>)}</div></section>
 <section className="panel"><div className="panelHead"><div><h3>Priority Skill Gaps</h3><p>Skills needing curriculum attention</p></div><button className="linkBtn" onClick={()=>navigate("gap")}>Analyze <ChevronRight size={15}/></button></div><div className="gapList">{gapData.slice(0,5).map(x=><div className="gapItem" key={x.skill}><div className={`gapIcon ${x.level.toLowerCase()}`}>{x.level==="High"?<AlertTriangle size={17}/>:x.level==="Medium"?<Clock3 size={17}/>:<CheckCircle2 size={17}/>}</div><div className="gapInfo"><strong>{x.skill}</strong><span>Industry {x.industry}% · Curriculum {x.curriculum}%</span></div><div className={`pill ${x.level.toLowerCase()}`}>{x.gap}% gap</div></div>)}</div></section></div>
 <section className="panel"><div className="panelHead"><div><h3>How SkillSync Works</h3><p>From raw job descriptions to actionable curriculum insights</p></div></div><div className="steps">{[["01","Collect","Job descriptions & industry requirements"],["02","Extract","NLP identifies relevant skills"],["03","Compare","Industry demand vs curriculum"],["04","Recommend","Priority actions & training areas"]].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div></section>
 </>}

function Analyzer({type,initial,onResult}){
 const isJob=type==="job";const [text,setText]=useState(initial),[skills,setSkills]=useState({}),[loading,setLoading]=useState(false),[done,setDone]=useState(false);
 async function analyze(){setLoading(true);try{const res=await fetch(`${API}/api/analyze-${isJob?"job":"curriculum"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(!res.ok)throw new Error();const d=await res.json();setSkills(d.skills);onResult(d.skills)}catch{const map=isJob?fallback.job_skills:fallback.curriculum_skills,found={};Object.entries(map).forEach(([k,v])=>{if(text.toLowerCase().includes(k.toLowerCase().split("/")[0]))found[k]=v});setSkills(found);onResult(found)}setDone(true);setLoading(false)}
 return <><PageHeader eyebrow={isJob?"NLP ANALYZER":"ACADEMIC ANALYZER"} title={isJob?"Job Description Analyzer":"Curriculum Analyzer"} desc={isJob?"Paste a job description and let the NLP engine extract the skills employers are asking for.":"Enter your curriculum, syllabus or training content to identify the skills currently being taught."}/>
 <div className="analyzerGrid"><section className="panel"><div className="panelHead"><div><h3>{isJob?"Job Description":"Curriculum / Training Content"}</h3><p>{isJob?"Paste the text from an employer job posting.":"Paste subjects, syllabus topics, labs and training modules."}</p></div><span className="miniTag"><BrainCircuit size={13}/> NLP</span></div><textarea className="bigTextarea" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste content here..."></textarea><div className="inputFooter"><span>{text.length} characters</span><button className="secondary"><Upload size={16}/> Upload File</button></div><button className="primary full" onClick={analyze} disabled={loading}>{loading?"Analyzing...":<><Sparkles size={17}/> Analyze {isJob?"Job":"Curriculum"}</>}</button></section>
 <section className="panel resultPanel"><div className="panelHead"><div><h3>Detected Skills</h3><p>{done?`${Object.keys(skills).length} relevant skills identified`:"Results will appear here after analysis"}</p></div>{done&&<span className="successTag"><CheckCircle2 size={14}/> Complete</span>}</div>{!done?<div className="emptyState"><BrainCircuit size={44}/><strong>Ready for analysis</strong><p>Click the button to run the skill extraction engine.</p></div>:<div className="detected">{Object.entries(skills).sort((a,b)=>b[1]-a[1]).map(([skill,score])=><div className="detectedItem" key={skill}><div className="skillTitle"><span>{skill}</span><b>{score}%</b></div><div className="barTrack"><div className="barFill" style={{width:`${score}%`}}></div></div><small>{score>=75?"Strong signal":score>=55?"Relevant signal":"Emerging signal"}</small></div>)}</div>}</section></div></>}

function GapPage({gapData}){
 const pie=[{name:"High",value:gapData.filter(x=>x.level==="High").length},{name:"Medium",value:gapData.filter(x=>x.level==="Medium").length},{name:"Low",value:gapData.filter(x=>x.level==="Low").length}],COLORS=["#f04438","#f59e0b","#20a36a"];
 return <><PageHeader eyebrow="CORE ANALYSIS" title="Skill Gap Analysis" desc="Compare the skills demanded by industry against the skills represented in the current curriculum." action={<button className="secondary" onClick={()=>window.print()}><Download size={16}/> Export Report</button>}/>
 <div className="gapSummary"><div className="summaryCard"><Target/><span>Skills Compared</span><strong>{gapData.length}</strong></div><div className="summaryCard high"><AlertTriangle/><span>High Priority</span><strong>{pie[0].value}</strong></div><div className="summaryCard medium"><Clock3/><span>Medium Priority</span><strong>{pie[1].value}</strong></div><div className="summaryCard low"><CheckCircle2/><span>Low Priority</span><strong>{pie[2].value}</strong></div></div>
 <div className="twoCol"><section className="panel"><div className="panelHead"><div><h3>Industry vs Curriculum</h3><p>Coverage percentage comparison</p></div></div><div className="chartBox"><ResponsiveContainer width="100%" height={330}><BarChart data={gapData.slice(0,8)} margin={{left:-15,right:10,top:10,bottom:60}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="skill" angle={-35} textAnchor="end" interval={0} height={75}/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="industry" name="Industry" fill="#315efb" radius={[5,5,0,0]}/><Bar dataKey="curriculum" name="Curriculum" fill="#a9b7d5" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section>
 <section className="panel"><div className="panelHead"><div><h3>Gap Distribution</h3><p>Priority classification</p></div></div><div className="pieWrap"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={pie} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={65} outerRadius={95} paddingAngle={4}>{pie.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{pie.map((x,i)=><span key={x.name}><i style={{background:COLORS[i]}}></i>{x.name}: {x.value}</span>)}</div></div></section></div>
 <section className="panel"><div className="panelHead"><div><h3>Detailed Skill Gap Matrix</h3><p>Use this table during your project review to explain priority gaps.</p></div></div><div className="tableWrap"><table><thead><tr><th>Skill</th><th>Industry Demand</th><th>Curriculum</th><th>Gap</th><th>Priority</th></tr></thead><tbody>{gapData.map(x=><tr key={x.skill}><td><strong>{x.skill}</strong></td><td>{x.industry}%</td><td>{x.curriculum}%</td><td><b>{x.gap}%</b></td><td><span className={`pill ${x.level.toLowerCase()}`}>{x.level}</span></td></tr>)}</tbody></table></div></section></>}

function Trends({data}){return <><PageHeader eyebrow="MARKET INTELLIGENCE" title="Industry Skill Trends" desc="A view of the skills currently showing strong demand in the project’s analyzed job-market dataset."/><section className="panel"><div className="panelHead"><div><h3>Demand by Skill</h3><p>Higher score indicates stronger demand signal.</p></div></div><div className="chartBox"><ResponsiveContainer width="100%" height={390}><BarChart data={data} margin={{left:-15,right:20,top:10,bottom:70}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="skill" angle={-35} textAnchor="end" interval={0} height={85}/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="demand" fill="#315efb" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></section><div className="trendGrid">{data.map((x,i)=><div className="trendCard" key={x.skill}><div className="trendTop"><span className="trendRank">#{i+1}</span><span>{x.category}</span></div><h3>{x.skill}</h3><div className="trendScore">{x.demand}<small>/100</small></div><div className="barTrack"><div className="barFill" style={{width:`${x.demand}%`}}></div></div><p>{x.demand>=80?"Very high demand":x.demand>=70?"High demand":"Growing demand"}</p></div>)}</div></>}

function Recommendations({gapData}){const high=gapData.filter(x=>x.gap>=35),medium=gapData.filter(x=>x.gap>=15&&x.gap<35),recs=[...high.map(x=>({level:"High Priority",skill:x.skill,text:`Add practical training and assessment coverage for ${x.skill}. Industry demand is ${x.industry}% while curriculum coverage is ${x.curriculum}%.`})),...medium.map(x=>({level:"Medium Priority",skill:x.skill,text:`Strengthen ${x.skill} through projects, labs or updated learning modules to reduce the ${x.gap}% gap.`}))];return <><PageHeader eyebrow="AI INSIGHTS" title="AI Recommendations" desc="Actionable suggestions generated from the detected industry–curriculum skill gaps." action={<span className="aiBadge"><Sparkles size={15}/> Recommendation Engine</span>}/><div className="recommendHero"><div className="recommendIcon"><BrainCircuit size={34}/></div><div><h2>Curriculum improvement plan</h2><p>The highest-impact changes should target skills where industry demand significantly exceeds current curriculum coverage.</p></div></div><div className="recommendList">{recs.length?recs.map((r,i)=><div className="recommendCard" key={r.skill}><div className="recNumber">{String(i+1).padStart(2,"0")}</div><div className="recBody"><div><span className="pill high">{r.level}</span><h3>{r.skill}</h3></div><p>{r.text}</p><div className="recActions"><span><BookOpen size={15}/> Curriculum module</span><span><Activity size={15}/> Practical project</span><span><BriefcaseBusiness size={15}/> Industry exposure</span></div></div></div>):<div className="emptyState"><CheckCircle2 size={44}/><strong>Good alignment</strong><p>No major recommendations found.</p></div>}</div></>}

function Profile(){const skills=[["Python",82],["SQL",74],["Data Analysis",78],["Machine Learning",55],["Power BI",45],["Cloud Computing",32]];return <><PageHeader eyebrow="STUDENT PROFILE" title="My Skill Profile" desc="A student-facing view for comparing current capabilities with target roles."/><div className="profileHead"><div className="profileAvatar">SR</div><div><h2>Satya Rameshwarapu</h2><p>Final Year · Computer Science & Engineering</p><div className="profileTags"><span>Data Analytics</span><span>AI / ML</span><span>Software</span></div></div><button className="secondary"><Settings size={16}/> Edit Profile</button></div><div className="profileGrid"><section className="panel"><div className="panelHead"><div><h3>Current Skills</h3><p>Self-assessment / project-based profile</p></div></div>{skills.map(([s,v])=><div className="profileSkill" key={s}><div><strong>{s}</strong><span>{v}%</span></div><div className="barTrack"><div className="barFill" style={{width:`${v}%`}}></div></div></div>)}</section><section className="panel targetPanel"><div className="targetCircle"><strong>68%</strong><span>Target role match</span></div><h3>Suggested next skills</h3>{["Cloud Computing","Power BI","Advanced SQL"].map(s=><div className="nextSkill" key={s}><CheckCircle2 size={16}/>{s}<ChevronRight size={16}/></div>)}</section></div></>}

function Reports({data,gapData}){const avg=gapData.length?Math.round(gapData.reduce((a,x)=>a+x.gap,0)/gapData.length):0;return <><PageHeader eyebrow="PROJECT REPORT" title="Analysis Report" desc="A presentation-ready summary of the current SkillSync analysis." action={<button className="primary" onClick={()=>window.print()}><Download size={16}/> Print / Save PDF</button>}/><section className="reportHero"><div><span>SKILLSYNC AI</span><h2>Industry–Academia Skill Gap Report</h2><p>Generated from job-market requirements and curriculum analysis.</p></div><div className="reportScore"><strong>{72-Math.min(avg,20)}%</strong><span>Alignment</span></div></section><div className="statsGrid"><Stat icon={BriefcaseBusiness} label="Job Dataset" value="1,240" delta="Analyzed postings" tone="blue"/><Stat icon={BrainCircuit} label="Skills" value={Object.keys(data.job_skills).length} delta="Detected" tone="purple"/><Stat icon={Target} label="Avg Gap" value={`${avg}%`} delta="Across compared skills" tone="orange"/><Stat icon={Gauge} label="Status" value="Active" delta="Continuous monitoring" tone="green"/></div><section className="panel"><div className="panelHead"><div><h3>Executive Findings</h3></div></div><ul className="findings"><li>Technology and employer expectations are changing continuously, requiring regular skill-gap analysis.</li><li>Skills with the largest gaps should receive priority in curriculum and practical-training updates.</li><li>NLP-style extraction makes it possible to process many job descriptions and identify repeated skill requirements.</li><li>The analysis can support stronger industry–academic collaboration and student employability.</li></ul></section></>}

export default App;
